name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t apptest-cicd:latest .
