name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Construir imagen Docker
      run: |
        docker build -t my-app:latest .

    - name: Push de la imagen al registro
      run: |
        docker tag my-app:latest localhost:5000/my-app:latest
        docker push localhost:5000/my-app:latest

    - name: Desplegar en k3s
      run: |
        kubectl set image deployment/my-app my-app=localhost:5000/my-app:latest --namespace=default

