name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t apptest-cicd:latest .

    - name: Push image to docker registry
      run: |
        docker tag apptest-cicd:latest aioria84/apptest-devops:v3
        docker push aioria84/apptest-devops:v3

    - name: Create Namespace apptest
      run: |
        kubectl create ns apptest

    - name: Deploy app
      run: |
         kubectl apply -f k8s/
